[package]
name = "factory_anchor_long"
version = "0.8.0"
authors = [
  "Frank Hillard <frank.hillard@gmail.com>",
  "Jeremy Martin <jeremy.martin@smart-chain.fr>"
]
description = "Factory of anchoring contracts."
readme = "README.md"
license = "MIT"
keywords = ["factory", "anchor", "starknet"]

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.3.0"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.10.2" }

[cairo]
sierra-replace-ids = true

[[target.starknet-contract]]
casm = true

# build-external-contracts = ["openzeppelin::account::account::Account"]

[scripts]
test = "snforge test factory_anchor_long"